-- Insert location data
INSERT INTO locations (name, created_at, updated_at)
VALUES
    ('2nd Floor Restroom', now(), now()),
    ('Air Compressor Area', now(), now()),
    ('AHU Area 1', now(), now()),
    ('AHU Area 2', now(), now()),
    ('Boiler Room', now(), now()),
    ('Building & Grounds', now(), now()),
    ('Capsule Machine Room', now(), now()),
    ('Colorant Storage', now(), now()),
    ('Corrugated Storage', now(), now()),
    ('Employee Break Room', now(), now()),
    ('Employee Parking', now(), now()),
    ('Employee Restroom', now(), now()),
    ('Front Office', now(), now()),
    ('Front Office Parking', now(), now()),
    ('Front Office Restrooms', now(), now()),
    ('Loading Dock', now(), now()),
    ('Maintenance Office', now(), now()),
    ('Maintenance Shop', now(), now()),
    ('Maintenance Storage', now(), now()),
    ('Manufacturing Area 1', now(), now()),
    ('Manufacturing Area 2', now(), now()),
    ('Process Water Room', now(), now()),
    ('Product Storage 2nd Floor', now(), now()),
    ('Product Storage Rear', now(), now()),
    ('Production Mgr Office', now(), now()),
    ('Production Office', now(), now()),
    ('QA Inspection', now(), now()),
    ('QA Office', now(), now()),
    ('Resin Storage', now(), now()),
    ('Secondary Room', now(), now()),
    ('Shipping & Receiving', now(), now()),
    ('Tooling Area', now(), now()),
    ('Tooling Area Restrooms', now(), now()),
    ('Ultrasonic Welding Room', now(), now())
ON CONFLICT (name) DO NOTHING;
